version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "release"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    reopen-dependabot-prs: true

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "release"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "release"
    schedule:
      interval: "weekly"
